# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-analyze:
    name: Install contrast-maven-plugin snapshot
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'

      - name: Checkout contrast-maven-plugin snapshot
        uses: actions/checkout@v2
        with:
          repository: Contrast-Security-OSS/contrast-maven-plugin
          ref: java-3292-scan
          path: contrast-maven-plugin

      - name: Install contrast-maven-plugin snapshot
        working-directory: contrast-maven-plugin
        run: ./mvnw --batch-mode -DskipTests install
        
      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Build and Run Contrast Scan
        run: ./mvnw --batch-mode -Pcontrast-scan verify
        env:
          CONTRAST__API__URL: https://teamserver-staging.contsec.com/Contrast/api
          CONTRAST__API__ORGANIZATION_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          CONTRAST__API__USER_NAME: ${{ secrets.CONTRAST__API__USER_NAME }}
          CONTRAST__API__API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
          CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
      
